name: Create New Puzzles and Commit Changes

on:
  schedule:
    # Runs at 20:00 EST (01:00 UTC) on Tuesdays and Fridays
    - cron: "0 1 * * 2,5"

jobs:
  run-game-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false # we will set up our own token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: gen-lang-client-0608167298
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script (EN)
        run: |
          python scripts/game.py daily --language en
          python scripts/game.py daily --language fr

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --cached --quiet || git commit -m "scheduled puzzle generation: $(date -u '+%Y-%m-%d %H:%M UTC')"
          git push
        env:
          # Use GitHub token to push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
